name: basic_login_signup
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
    sdk: ^3.8.1

dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.8
    firebase_core: ^3.15.1
    firebase_auth: ^5.6.2
    cloud_firestore: ^5.6.11
    get: ^4.7.2
    google_sign_in: ^6.2.1 # the latest version is 7.1.1 but we are using some issue is login() function in login.dart, and that's why we decreased the version


dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^6.0.0

# The following section is specific to Flutter packages.
flutter:
    uses-material-design: true

    assets:
        - asset/images/

    fonts:
        - family: Caprasimo
          fonts:
              - asset: asset/fonts/Caprasimo/Caprasimo-Regular.ttf

        - family: Luckiest_Guy
          fonts:
              - asset: asset/fonts/Luckiest_Guy/LuckiestGuy-Regular.ttf

        - family: Lora
          fonts:
              - asset: asset/fonts/Lora/Lora-VariableFont_wght.ttf
